mask_disney_elena:
  type: data
  display_data:
    category: Adriftus
    material: sunflower
    display_name: <&f>Disney<&co> <&e>Elena
    description: "<&e>Elena of Avalor!"
  mask_data:
    id: disney_elena
    display_name: <&e>Elena
    skin_blob: ewogICJ0aW1lc3RhbXAiIDogMTY1MTg2ODAzMTU4MCwKICAicHJvZmlsZUlkIiA6ICIwMGZiNTRiOWI4NDA0YTA0YTViMmJhMzBlYzBlYTAxMiIsCiAgInByb2ZpbGVOYW1lIiA6ICJrbGxveWQ3MCIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mMDZlOTBhYjQ1NzVmNDJhMTE5YTQ1NjI4Yzc0MWQwZTZkYmQyZjExMmMzM2YxYzU4NjQ5MTQ4ZjhjN2M1M2NlIiwKICAgICAgIm1ldGFkYXRhIiA6IHsKICAgICAgICAibW9kZWwiIDogInNsaW0iCiAgICAgIH0KICAgIH0KICB9Cn0=;QI3r4oo7CV2ulDCO8aJOfxXohd/1SJ2dyU4zXmO/XP7aJAu3nmWdlovLHMe3hv+PQOmnpL2jL3R7Tkt03OCJ2ciJrQHGaQQ2wgrBbIx9gReqrO+nh+lPAlnWfdQc905ZpoakArim4/fRAvgqUckfYk1mqb0s+TDW0OjZUPBhBPddV9/IEvr9r5/u1zBTPhZZIBu5M7AAdAnHyVEEOksfYHgKHI1Ipb3QsHVWsNrarvRVbhPiK8szhqzYkQr0ubX193/cCPv6oxub97EV5GruNpkAT1eMyTbmVjPT1UUEo6xhiUa8cT1hGRBZKn3AzCWzEES5HXODb2NRfnfTbbXFZ8mngyhNYSlTlv/6rVBrLGNpTzs2NQyDUDOOV8yAmKLbkFaTbIkEAU0M2WjN4z2ok7nsXOF1GUT+iRlCkCwVqLdtG7LdxdnqKiibPSHhVJF46ydMhWuoGuAw3QfHthXATDr+sfg6jc8BkKDU9Y8S2RwhjroM8kEMYctPzNt/HLvwkrSQkpWDcW6rx44iUaFLCoAZMZnV6NzYzpE5XepSMP2ZexBZGWs+sYTljcCVlqNTpmh7tMftgf9J/TCDIQPydkCHrP6vPWA0XfngfggPr8Bl7e7+cPlBkqaNUiJZj00P1nLoFRmZHfg56ZKhLutcmzKU054z+f3amloIvXp+By8=