mask_encanto_pepa:
  type: data
  display_data:
    category: Encanto
    material: sunflower
    display_name: <&b>Encanto<&co> <&e>Pepa
    description: "<&e>Pepa<&e> from <&6>Encanto"
  mask_data:
    id: encanto_pepa
    display_name: <&e>Pepa
    skin_blob: ewogICJ0aW1lc3RhbXAiIDogMTY0NzE5ODYzMTAyMCwKICAicHJvZmlsZUlkIiA6ICIyMWUzNjdkNzI1Y2Y0ZTNiYjI2OTJjNGEzMDBhNGRlYiIsCiAgInByb2ZpbGVOYW1lIiA6ICJHZXlzZXJNQyIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9hMzhjMTU1OWU2ZGU5MjgwMWFhZjc4NzljZTZiYjc5MmZkNzRiYzM2YWYyNTdlNmUxZTQ2ZWEyNTI5YWNlNjk0IiwKICAgICAgIm1ldGFkYXRhIiA6IHsKICAgICAgICAibW9kZWwiIDogInNsaW0iCiAgICAgIH0KICAgIH0KICB9Cn0=;CpMcTJCHmkm1Bjfi7Y+342v6UON0kDRr+S9VrdAvP6funBhLp/cOb2l83xsH6kaFGGVTHbw1NO9MkQMHBX0ylopdgjQcvj3Fl2DJKnJVm+AceHcSqu+J9lDhfpwVQq732GNay0XsGGTeKBoyLtTm89LwkV/pTWMypxorOaeqRahADM16j7G+OLsQ/gmAc0LNZtQYqvEJ7WsASjQU1jgZs4PfqNnrNjvxwTDvWf5hcB4C4g0kd2YBgMvmBw2TlghEKU0xqDvv2M+qZpNL3DfF/1FUKDd7yiIkPyJatZU4MMXs0bOttGNAKvJBuRVJIT5yxUAZiye77C3bDGhopMlnslu98gdcel8XEmxAdP0d/F+D7+Q7cYk7WH3gvlzSUqQem7sJmjlw84zn7xp9SfHrpVyTtzop63IlTBls16XTmM+PCgwUR+3Pz/WJcQs+o9Hyx6wldloBC9SFN8mm/6x6YZiQJBrFbzRQ7umQWfcdHnCLlIzLyebtYyYTkNZiP2AEGi086y0gQOLqqfPiIPlPd1gZTlMUHQ0cinEJvMclCstFxK9+h48AyaxzhlSlLaPWGVW8/qTCynXMwU2kmWobmn6xFBqTUDwg0FazkYNAEe6yy8gMJxDIrAfVgx4G8t5cZKbD+iqDAUopqMLchHu8ZGgcxKULSfaFexqdkfUA0ks=